// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, email, password_hash)
VALUES (?, ?, ?)
RETURNING id, name, email, password_hash, created_at
`

type CreateAgentParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent, arg.Name, arg.Email, arg.PasswordHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByEmail = `-- name: GetAgentByEmail :one
SELECT id, name, email, password_hash, created_at FROM agents WHERE email = ? LIMIT 1
`

func (q *Queries) GetAgentByEmail(ctx context.Context, email string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByEmail, email)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, email, password_hash, created_at FROM agents WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentByID(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
